// Standard ISO 3166-1 numeric country codes -> [name, continent].
// Used to color each landmass by continent and to identify countries
// from the topojson feature ids (world-atlas uses these same codes).
export const COUNTRY_INFO = {
  4: ["Afghanistan", "Asia"], 8: ["Albania", "Europe"], 12: ["Algeria", "Africa"],
  16: ["American Samoa", "Oceania"], 20: ["Andorra", "Europe"], 24: ["Angola", "Africa"],
  28: ["Antigua and Barbuda", "North America"], 31: ["Azerbaijan", "Asia"],
  32: ["Argentina", "South America"], 36: ["Australia", "Oceania"], 40: ["Austria", "Europe"],
  44: ["Bahamas", "North America"], 48: ["Bahrain", "Asia"], 50: ["Bangladesh", "Asia"],
  51: ["Armenia", "Asia"], 52: ["Barbados", "North America"], 56: ["Belgium", "Europe"],
  60: ["Bermuda", "North America"], 64: ["Bhutan", "Asia"], 68: ["Bolivia", "South America"],
  70: ["Bosnia and Herzegovina", "Europe"], 72: ["Botswana", "Africa"], 76: ["Brazil", "South America"],
  84: ["Belize", "North America"], 90: ["Solomon Islands", "Oceania"],
  92: ["British Virgin Islands", "North America"], 96: ["Brunei", "Asia"], 100: ["Bulgaria", "Europe"],
  104: ["Myanmar", "Asia"], 108: ["Burundi", "Africa"], 112: ["Belarus", "Europe"],
  116: ["Cambodia", "Asia"], 120: ["Cameroon", "Africa"], 124: ["Canada", "North America"],
  132: ["Cabo Verde", "Africa"], 136: ["Cayman Islands", "North America"],
  140: ["Central African Republic", "Africa"], 144: ["Sri Lanka", "Asia"], 148: ["Chad", "Africa"],
  152: ["Chile", "South America"], 156: ["China", "Asia"], 158: ["Taiwan", "Asia"],
  162: ["Christmas Island", "Oceania"], 166: ["Cocos Islands", "Oceania"],
  170: ["Colombia", "South America"], 174: ["Comoros", "Africa"], 175: ["Mayotte", "Africa"],
  178: ["Congo", "Africa"], 180: ["DR Congo", "Africa"], 184: ["Cook Islands", "Oceania"],
  188: ["Costa Rica", "North America"], 191: ["Croatia", "Europe"], 192: ["Cuba", "North America"],
  196: ["Cyprus", "Asia"], 203: ["Czechia", "Europe"], 204: ["Benin", "Africa"],
  208: ["Denmark", "Europe"], 212: ["Dominica", "North America"],
  214: ["Dominican Republic", "North America"], 218: ["Ecuador", "South America"],
  222: ["El Salvador", "North America"], 226: ["Equatorial Guinea", "Africa"],
  231: ["Ethiopia", "Africa"], 232: ["Eritrea", "Africa"], 233: ["Estonia", "Europe"],
  234: ["Faroe Islands", "Europe"], 238: ["Falkland Islands", "South America"],
  242: ["Fiji", "Oceania"], 246: ["Finland", "Europe"], 250: ["France", "Europe"],
  254: ["French Guiana", "South America"], 258: ["French Polynesia", "Oceania"],
  260: ["French Southern Territories", "Antarctica"], 262: ["Djibouti", "Africa"],
  266: ["Gabon", "Africa"], 268: ["Georgia", "Asia"], 270: ["Gambia", "Africa"],
  275: ["Palestine", "Asia"], 276: ["Germany", "Europe"], 288: ["Ghana", "Africa"],
  292: ["Gibraltar", "Europe"], 296: ["Kiribati", "Oceania"], 300: ["Greece", "Europe"],
  304: ["Greenland", "North America"], 308: ["Grenada", "North America"],
  312: ["Guadeloupe", "North America"], 316: ["Guam", "Oceania"],
  320: ["Guatemala", "North America"], 324: ["Guinea", "Africa"], 328: ["Guyana", "South America"],
  332: ["Haiti", "North America"], 336: ["Vatican City", "Europe"],
  340: ["Honduras", "North America"], 344: ["Hong Kong", "Asia"], 348: ["Hungary", "Europe"],
  352: ["Iceland", "Europe"], 356: ["India", "Asia"], 360: ["Indonesia", "Asia"],
  364: ["Iran", "Asia"], 368: ["Iraq", "Asia"], 372: ["Ireland", "Europe"],
  376: ["Israel", "Asia"], 380: ["Italy", "Europe"], 384: ["Cote d'Ivoire", "Africa"],
  388: ["Jamaica", "North America"], 392: ["Japan", "Asia"], 398: ["Kazakhstan", "Asia"],
  400: ["Jordan", "Asia"], 404: ["Kenya", "Africa"], 408: ["North Korea", "Asia"],
  410: ["South Korea", "Asia"], 414: ["Kuwait", "Asia"], 417: ["Kyrgyzstan", "Asia"],
  418: ["Laos", "Asia"], 422: ["Lebanon", "Asia"], 426: ["Lesotho", "Africa"],
  428: ["Latvia", "Europe"], 430: ["Liberia", "Africa"], 434: ["Libya", "Africa"],
  438: ["Liechtenstein", "Europe"], 440: ["Lithuania", "Europe"], 442: ["Luxembourg", "Europe"],
  446: ["Macao", "Asia"], 450: ["Madagascar", "Africa"], 454: ["Malawi", "Africa"],
  458: ["Malaysia", "Asia"], 462: ["Maldives", "Asia"], 466: ["Mali", "Africa"],
  470: ["Malta", "Europe"], 474: ["Martinique", "North America"], 478: ["Mauritania", "Africa"],
  480: ["Mauritius", "Africa"], 484: ["Mexico", "North America"], 492: ["Monaco", "Europe"],
  496: ["Mongolia", "Asia"], 498: ["Moldova", "Europe"], 499: ["Montenegro", "Europe"],
  500: ["Montserrat", "North America"], 504: ["Morocco", "Africa"], 508: ["Mozambique", "Africa"],
  512: ["Oman", "Asia"], 516: ["Namibia", "Africa"], 520: ["Nauru", "Oceania"],
  524: ["Nepal", "Asia"], 528: ["Netherlands", "Europe"], 540: ["New Caledonia", "Oceania"],
  548: ["Vanuatu", "Oceania"], 554: ["New Zealand", "Oceania"], 558: ["Nicaragua", "North America"],
  562: ["Niger", "Africa"], 566: ["Nigeria", "Africa"], 570: ["Niue", "Oceania"],
  574: ["Norfolk Island", "Oceania"], 578: ["Norway", "Europe"],
  580: ["Northern Mariana Islands", "Oceania"], 583: ["Micronesia", "Oceania"],
  584: ["Marshall Islands", "Oceania"], 585: ["Palau", "Oceania"], 586: ["Pakistan", "Asia"],
  591: ["Panama", "North America"], 598: ["Papua New Guinea", "Oceania"],
  600: ["Paraguay", "South America"], 604: ["Peru", "South America"], 608: ["Philippines", "Asia"],
  612: ["Pitcairn Islands", "Oceania"], 616: ["Poland", "Europe"], 620: ["Portugal", "Europe"],
  624: ["Guinea-Bissau", "Africa"], 626: ["Timor-Leste", "Asia"],
  630: ["Puerto Rico", "North America"], 634: ["Qatar", "Asia"], 642: ["Romania", "Europe"],
  643: ["Russia", "Asia"], 646: ["Rwanda", "Africa"], 652: ["Saint Barthelemy", "North America"],
  654: ["Saint Helena", "Africa"], 659: ["Saint Kitts and Nevis", "North America"],
  660: ["Anguilla", "North America"], 662: ["Saint Lucia", "North America"],
  663: ["Saint Martin", "North America"], 666: ["Saint Pierre and Miquelon", "North America"],
  670: ["Saint Vincent and the Grenadines", "North America"], 674: ["San Marino", "Europe"],
  678: ["Sao Tome and Principe", "Africa"], 682: ["Saudi Arabia", "Asia"],
  686: ["Senegal", "Africa"], 688: ["Serbia", "Europe"], 690: ["Seychelles", "Africa"],
  694: ["Sierra Leone", "Africa"], 702: ["Singapore", "Asia"], 703: ["Slovakia", "Europe"],
  704: ["Vietnam", "Asia"], 705: ["Slovenia", "Europe"], 706: ["Somalia", "Africa"],
  710: ["South Africa", "Africa"], 716: ["Zimbabwe", "Africa"], 724: ["Spain", "Europe"],
  728: ["South Sudan", "Africa"], 729: ["Sudan", "Africa"], 732: ["Western Sahara", "Africa"],
  740: ["Suriname", "South America"], 748: ["Eswatini", "Africa"], 752: ["Sweden", "Europe"],
  756: ["Switzerland", "Europe"], 760: ["Syria", "Asia"], 762: ["Tajikistan", "Asia"],
  764: ["Thailand", "Asia"], 768: ["Togo", "Africa"], 772: ["Tokelau", "Oceania"],
  776: ["Tonga", "Oceania"], 780: ["Trinidad and Tobago", "North America"],
  784: ["United Arab Emirates", "Asia"], 788: ["Tunisia", "Africa"], 792: ["Turkey", "Asia"],
  795: ["Turkmenistan", "Asia"], 796: ["Turks and Caicos Islands", "North America"],
  798: ["Tuvalu", "Oceania"], 800: ["Uganda", "Africa"], 804: ["Ukraine", "Europe"],
  807: ["North Macedonia", "Europe"], 818: ["Egypt", "Africa"], 826: ["United Kingdom", "Europe"],
  831: ["Guernsey", "Europe"], 832: ["Jersey", "Europe"], 833: ["Isle of Man", "Europe"],
  834: ["Tanzania", "Africa"], 840: ["United States", "North America"],
  850: ["US Virgin Islands", "North America"], 854: ["Burkina Faso", "Africa"],
  858: ["Uruguay", "South America"], 860: ["Uzbekistan", "Asia"], 862: ["Venezuela", "South America"],
  876: ["Wallis and Futuna", "Oceania"], 882: ["Samoa", "Oceania"], 887: ["Yemen", "Asia"],
  894: ["Zambia", "Africa"],
};
